apiVersion: v1
kind: Secret
metadata:
  name:  ssh-user
data:
   username: ssh-user
   password: very-secure-password
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssh-tunnel
spec:
  replicas: 5
  selector:
    matchLabels:
      app: ssh-tunnel
  template:
    metadata:
      labels:
        app: ssh-tunnel
    spec:
      containers:
      - name: ssh-tunnel
        image: ghcr.io/mroplus/restricted-ssh-tunnel:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 22
        env:
          - name: SSH_USERNAME
            valueFrom:
              secretKeyRef:
                name: ssh-user
                key: username
          - name: SSH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ssh-user
                key: password
